import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Vendored SHOP.CO reference implementation: read-only asset and design
    // source, not part of this application's build.
    "shop.co/**",

    // Generated by `prisma generate`; regenerated on every build.
    "app/generated/**",
  ]),
]);

export default eslintConfig;
